### ISSUE TITLE
Collapse state not being maintained

### ISSUE THREAD

**Issue by JoeFirebaugh** [rath/angular-folding#12]
First, I want to thank you for this plugin!   There's just a few issues that could be fixed to make it perfect.

1. The collapse/expanded state is constantly being forgotten.   It seems that every file change/save causes the folding to collapse, which almost makes it too frustrating to use.  I find that just saving or sometimes tabbing between my open files seems to cause all of them to collapse.
2. It would be extra nice if the VCS status coloring (not added, changed, etc) was propagated up to the fold node.   So that you have some sort of visibility that you have files that need to be added to GIT or HG.  Although, this feature is needed less if the folded node stayed expanded so I can see the children while working.

Thanks!

**Comment by rath** [comment]
Closing this issue as it has been open for over several years and is no longer applicable due to major updates in the project. Please reopen or create a new issue if this persists in the latest version.
