### ISSUE TITLE
Add actions/effects/reducer/selectors to file pattern (or maybe make the pattern configurable)

### ISSUE THREAD

**Issue by MassiveHiggsField** [rath/angular-folding#14]
First of all, great work, super helpful plugin :). The rest is all pretty much in the title. Would be awesome to add these to the file pattern or maybe make the regex configurable.

**Comment by MassiveHiggsField** [comment]
PS: maybe even add singular and plural versions of these

**Comment by jalberto-ghub** [comment]
Also would be nice to make possible to support other schematics like support for nativescript-angular.
In that case one would like *.tns.(ts|html|css|sccs) and so on to be part of the virtual folder.

**Comment by fsomme2s** [comment]
+1 for "make the pattern configurable"

I'd like to use the filename pattern "foobar**.view**" instead of "foobar.view.component" for a certain type of component

**Comment by rusranx** [comment]
#18
