### ISSUE TITLE
Make it possible to configure open action

### ISSUE THREAD

**Issue by steve-todorov** [rath/angular-folding#19]
Thanks for this great plugin! I would like to make a suggestion - it would be nice if when you double click on a folded component it automatically opens the `.ts` file which is most likely where you would like to go. Maybe also make it configurable for people who might want it configured differently?

**Comment by rath** [comment]
Closing this issue as it has been open for over several years and is no longer applicable due to major updates in the project. Please reopen or create a new issue if this persists in the latest version.
