### ISSUE TITLE
Service is folded into .component.

### ISSUE THREAD

**Issue by EPILock** [rath/angular-folding#7]
- xxx.service.ts is folder into xxx.component
- single file (like xxx.service.ts) should not be folded

**Comment by henriquecm** [comment]
Similar error here, when files are folded into a virtual folder, instead of showing the file extension like before is only showing .component, so I have to identify which file this is by the file icon.

**Comment by DaSchTour** [comment]
But it should work this way
* xxx.component.ts
* xxx.component.spec.ts
* xxx.service.ts
* xxx.service.spec.ts

should be
* (C) xxx
  * .ts
  * .spec.ts
* (S) xxx
  * .ts
  * .spec.ts

I hope it's clear what I wanted to show. Services should still be folded together with their spec file.

**Comment by henriquecm** [comment]
What is happening is:

Case 1:
Files: user.service.ts, user.spec.ts
- user.component
    - .service
    - .service


Case 2:
Files: auth.guard.ts, auth.guard.spec.ts
- auth.component
    - .guard
    - .guard


Case 3:
Files: home.component.ts, home.component.spec.ts, home.component.css, home.component.html, home.component.scss
- home.component
    - .component
    - .component
    - .component
    - .component
    - .component


The file extension is only visible on the file icon, in the .spec.ts case I have to open the file to know if is the .ts or the .spec.ts

**Comment by henriquecm** [comment]
Also, I think with only one file, there no need to fold, because then first you have to open the folder then the file, an unnecessary additional step.
I don't use .spec.ts with services and guards, I only created them to see how they would fold.

**Comment by rath** [comment]
Fixed them at version 1.3.
I have submitted the patch today, and it usually takes 3 days for approval by jetbrains.

**Comment by DaSchTour** [comment]
Thx. Great work
