### ISSUE TITLE
Plugin does not apply any folding in WebStorm 2018.1.1

### ISSUE THREAD

**Issue by willydee** [rath/angular-folding#8]
As seen in the screenshot, components are still displayed separately in the project view, not grouped.

![screenshot from 2018-04-13 14-20-54](https://user-images.githubusercontent.com/7428576/38734531-4cb714b6-3f26-11e8-829a-867815d1382e.png)

### Plugin version
1.3.0

### System info
```
WebStorm 2018.1.1
Build #WS-181.4445.68, built on April 9, 2018
JRE: 1.8.0_152-release-1136-b27 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.15-63.current
```

**Comment by rath** [comment]
Closing this issue as it has been open for over 6 years and is no longer applicable due to major updates in the project. Please reopen or create a new issue if this persists in the latest version.
